apiVersion: v1
kind: Namespace
metadata:
  name: fintech
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fintech
type: Opaque
stringData:
  POSTGRES_USER: finuser
  POSTGRES_PASSWORD: finpass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fintech
data:
  POSTGRES_DB: finsecure
  POSTGRES_HOST: db   # nombre del Service de postgres
